version: '3.8'

services:
  # 1. Service Aplikasi Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # 2. Service Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - node

  # 3. Service Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/inventaris_bersih.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. Service Node.js (Vite frontend)
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: vite_node
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host

volumes:
  pgdata:
