# Gunakan base image Node.js versi 23
FROM node:22

# Set direktori kerja
WORKDIR /var/www

# Salin package.json dan package-lock.json terlebih dahulu untuk caching
COPY package.json package-lock.json ./

# Install dependensi Node.js
RUN npm install

# Salin sisa file proyek
COPY . .

# Expose port Vite
EXPOSE 5173

# Jalankan server development Vite
# Opsi --host sangat penting agar bisa diakses dari luar container
CMD ["npm", "run", "dev", "--", "--host"]